export enum TecnologiaFoco {
  IA_MACHINE_LEARNING = "IA & Machine Learning",
  IA_GENERATIVA = "IA Generativa",
  NLP = "Processamento de Linguagem Natural",
  VISAO_COMPUTACIONAL = "Visão Computacional",
  SISTEMAS_RECOMENDACAO = "Sistemas de Recomendação",
  BIG_DATA = "Big Data & Analytics",
  DATA_SCIENCE = "Data Science",
  MINERACAO_DADOS = "Mineração de Dados",
  ENGENHARIA_DADOS = "Engenharia de Dados",
  VISUALIZACAO_DADOS = "Visualização de Dados",
  BANCO_DE_DADOS = "Banco de Dados",
  RECUPERACAO_INFORMACAO = "Recuperação de Informação",
  BIOINFORMATICA = "Bioinformática",

  ENGENHARIA_SOFTWARE = "Engenharia de Software",
  ARQUITETURA_SOFTWARE = "Arquitetura de Software",
  QUALIDADE_SOFTWARE = "Qualidade de Software",
  TESTE_SOFTWARE = "Teste de Software",
  MANUTENCAO_SOFTWARE = "Manutenção & Evolução de Software",
  DESENVOLVIMENTO_SOLUCOES = "Desenvolvimento de Soluções",
  WEB_MOBILE = "Web & Mobile",
  DESENVOLVIMENTO_JOGOS = "Jogos Digitais",
  COMPUTACAO_GRAFICA = "Computação Gráfica",

  CLOUD_COMPUTING = "Cloud Computing",
  DEVOPS = "DevOps & Infraestrutura",
  MLOPS = "MLOps",
  SISTEMAS_DISTRIBUIDOS = "Sistemas Distribuídos",
  SISTEMAS_OPERACIONAIS = "Sistemas Operacionais",
  ARQUITETURA_COMPUTADORES = "Arquitetura de Computadores",
  REDES_COMPUTADORES = "Redes de Computadores",
  EDGE_COMPUTING = "Edge Computing",
  HPC = "Computação de Alto Desempenho",

  CYBERSECURITY = "Segurança & Criptografia",
  SEGURANCA_APLICACOES = "Segurança de Aplicações",
  PRIVACIDADE_DADOS = "Privacidade & Proteção de Dados",
  FORENSE_DIGITAL = "Forense Digital",
  LGPD_COMPLIANCE = "LGPD, Compliance & Gestão de Riscos",
  BLOCKCHAIN = "Blockchain & Web3",

  IHC = "Interação Humano-Computador",
  UX_UI = "UX/UI & Experiência do Usuário",
  ACESSIBILIDADE = "Acessibilidade Digital",
  EDUCACAO_DIGITAL = "Educação Digital",
  TECNOLOGIA_ASSISTIVA = "Tecnologia Assistiva",
  INCLUSAO_DIGITAL = "Inclusão Digital",
  IMPACTO_SOCIAL = "Tecnologia para Impacto Social",

  IOT_SISTEMAS_EMBARCADOS = "IoT & Sistemas Embarcados",
  ROBOTICA_AUTOMACAO = "Robótica & Automação",
  COMPUTACAO_UBIQUA = "Computação Ubíqua",
  INDUSTRIA_4_0 = "Indústria 4.0",

  ALGORITMOS_E_ESTRUTURAS = "Algoritmos & Estruturas de Dados",
  LINGUAGENS_E_COMPILADORES = "Linguagens & Compiladores",
  TEORIA_COMPUTACAO = "Teoria da Computação",
  METODOS_FORMAIS = "Métodos Formais & Verificação",
  OTIMIZACAO = "Otimização",
  COMPUTACAO_QUANTICA = "Computação Quântica",

  PESQUISA_ACADEMICA = "Pesquisa Acadêmica",
  INOVACAO_TECNOLOGICA = "Inovação Tecnológica",
  TRANSFORMACAO_DIGITAL = "Transformação Digital",
  EMPREENDEDORISMO_TECNOLOGICO = "Empreendedorismo Tecnológico",
  TRANSFERENCIA_TECNOLOGIA = "Transferência de Tecnologia",
  SUSTENTABILIDADE_TI = "TI Sustentável & Green IT",

  SAUDE_DIGITAL = "Saúde Digital",
  AGROTECH = "Agrotech & Tecnologia no Agro",
  SMART_CITIES = "Cidades Inteligentes",
  GOVTECH = "GovTech & Governo Digital",
  COMPUTACAO_APLICADA = "Computação Aplicada",

  EVENTO_CIENTIFICO = "Evento Científico",
  BOLSA_INICIACAO_CIENTIFICA = "Bolsa de Iniciação Científica",
  BOLSA_POS_GRADUACAO = "Bolsa de Pós-Graduação",
  INTERCAMBIO_PESQUISA = "Intercâmbio & Mobilidade em Pesquisa",
  RESIDENCIA_TECNOLOGICA = "Residência Tecnológica",

  MULTIDISCIPLINAR = "Multidisciplinar",
  OUTRO_COMPUTACAO = "Outro - Computação"
}

export enum TipoFerramenta {
  FRAMEWORK = "Framework",
  LINGUAGEM = "Linguagem de Programação",
  BANCO_DADOS = "Banco de Dados",
  IDE = "IDE/Editor",
  PLATAFORMA = "Plataforma",
  BIBLIOTECA = "Biblioteca/Pacote",
  FERRAMENTA_DESENVOLVIMENTO = "Ferramenta de Desenvolvimento",
  OUTRO = "Outro"
}
